### ISSUE TITLE
All references to microbadger.com fail as microbadger.com announced it was offline.

### ISSUE THREAD

**Issue by GPSBabelDeveloper** [purpleKarrot/build-containers#1]
https://github.com/purpleKarrot/build-containers references several resources on microbadger.com, but that domain was offlined on 2020-07-01. See:

http://web.archive.org/web/20210409135814/microbadger.com/shutdown

**Comment by purpleKarrot** [comment]
Thanks. I have replaced the badges with https://shields.io
